site_name: NEW INSIGHT ANALYTICS
site_url: https://awault.github.io/New_Insight
copyright: Copyright &copy 2024 | New Insight Analytics, LLC
extra:
  generator: false

theme:
  name: material
  palette: 
    scheme: default
    primary: custom
    accent: deep purple
  logo: assets/Big Logo.png
 
extra_css:
  - stylesheets/extra.css  

# Removes the default plugins such as search
plugins: []

